name: DPCPlugin
version: @version@
main: xyz.n7mn.dev.dpcplugin.DPCPlugin
api-version: 1.16
authors: [n3m_]
description: DPCPlugin
website: https://n7mn.xyz/
commands:
  dpc-vertical:
    description: '/dpc-vertical <URL>'
    usage: '/dpc-vertical'
  dpc-side:
    description: '/dpc-side <URL>'
    usage: '/dpc-side'